#!/usr/bin/env bash
# Regenerates references/catalogue.md from what is actually installed on disk.
# The router can only route over skills it knows exist, and skills come and go,
# so this is the one part of the skill that must never be hand-maintained.
#
# Run it after installing this skill, and again whenever you add or remove a
# pack. Shipping a catalogue from someone else's machine is the single way this
# skill produces confident, useless answers.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$HERE/references/catalogue.md"
SKILLS="${CLAUDE_SKILLS_DIR:-$HOME/.claude/skills}"
PLUGINS="${CLAUDE_PLUGINS_DIR:-$HOME/.claude/plugins/cache}"

# Pack attribution. gstack tags itself in its own description, so it is detected.
# The Matt Pocock engineering suite does not tag itself, so it is listed by name;
# that list is the one hand-maintained thing here, and it degrades gracefully —
# a skill missing from it simply lands under "Standalone".
MATT="ask-matt setup-matt-pocock-skills grilling grill-me grill-with-docs prototype
handoff to-spec to-tickets implement tdd code-review triage diagnosing-bugs wayfinder
improve-codebase-architecture codebase-design domain-modeling research to-questionnaire
wizard wait-what teach resolving-merge-conflicts writing-for-agents loop-me
migrate-to-shoehorn scaffold-exercises setup-pre-commit pick-ui-library"

desc() { awk '/^description:/{sub(/^description: **/,""); gsub(/^["'"'"']|["'"'"']$/,""); print; exit}' "$1"; }

emit() { # name, file
  local d; d=$(desc "$2")
  [ ${#d} -gt 240 ] && d="${d:0:237}..."
  # shellcheck disable=SC2016  # single quotes are deliberate: this is printf's
  # format string, and %s must reach printf unexpanded.
  printf -- '- `/%s` — %s\n' "$1" "$d"
}

{
  echo "# Installed skill catalogue"
  echo
  echo "Regenerated by \`scripts/build-catalogue.sh\`. Do not edit by hand."
  echo "Last generated: $(date +%Y-%m-%d)."
  echo
  echo "Never invoke a name that does not appear in this file."
  echo

  echo "## gstack"
  echo
  for f in "$SKILLS"/*/SKILL.md; do
    [ -e "$f" ] || continue
    n=$(basename "$(dirname "$f")"); case "$n" in _*) continue;; esac
    desc "$f" | grep -q '(gstack)' && emit "$n" "$f"
  done

  echo
  echo "## superpowers"
  echo
  for f in "$PLUGINS"/*/superpowers/*/skills/*/SKILL.md; do
    [ -e "$f" ] || continue
    emit "superpowers:$(basename "$(dirname "$f")")" "$f"
  done

  echo
  echo "## Matt Pocock engineering suite"
  echo
  for n in $MATT; do
    f="$SKILLS/$n/SKILL.md"; [ -e "$f" ] && emit "$n" "$f"
  done

  echo
  echo "## Standalone"
  echo
  for f in "$SKILLS"/*/SKILL.md; do
    [ -e "$f" ] || continue
    n=$(basename "$(dirname "$f")"); case "$n" in _*) continue;; esac
    desc "$f" | grep -q '(gstack)' && continue
    # tr pads a short destination set with its last character, so both spaces
    # and newlines become newlines: one name per line, ready for grep -x.
    echo "$MATT" | tr ' \n' '\n' | grep -qx "$n" && continue
    emit "$n" "$f"
  done
  # Plugin skills are invoked as `plugin:skill`, so that is how they must be
  # named here. temp_git_* are half-finished marketplace clones, not installs.
  for f in "$PLUGINS"/*/*/*/skills/*/SKILL.md; do
    [ -e "$f" ] || continue
    case "$f" in */superpowers/*|*/temp_git_*) continue;; esac
    plug=$(basename "$(dirname "$(dirname "$(dirname "$(dirname "$f")")")")")
    emit "$plug:$(basename "$(dirname "$f")")" "$f"
  done
} | awk '!/^- /{print; next} {k=$2} !seen[k]++' > "$OUT"

# ---------------------------------------------------------------------------
# Overlap detection.
#
# The arbitration this skill ships is fixed prose naming specific skills. The
# catalogue can filter it, but it cannot produce an argument for skills nobody
# has written about — that would be the confident, hollow output the whole skill
# exists to prevent.
#
# What IS derivable is the gap: you have three skills that all look like
# debuggers, and no published argument covers them. Saying so turns a limitation
# into a signal, and points at where a contribution would pay.
#
# Keyword matching on descriptions is crude and this is labelled as a signal,
# never a verdict. A missed overlap costs nothing; a claimed one that is wrong
# would cost trust.
# ---------------------------------------------------------------------------
ARB="$HERE/references/arbitration.md"
LOCAL_ARB="$HERE/references/arbitration.local.md"

terrains() {
  cat <<'TERRAINS'
debug|debug|diagnos|root cause
tdd|test-driven|red test|failing test|tdd
review|code review|pre-landing|review the diff|reviews the
framing|brainstorm|requirements|executable spec|design doc
splitting|ticket|triage|backlog
handover|handoff|context save|context restore|hand the session
skill-making|creating .*skill|writing skills|create .*skill
session-safety|destructive|guard rail|guardrail|restrict file edits
TERRAINS
}

# Written to a temp file first, then appended. Reading $OUT inside a block whose
# stdout is redirected onto $OUT is reading and writing one file in a single
# pipeline: it happens to work while the output is small, and stops being true
# without warning.
OVERLAP=$(mktemp)
trap 'rm -f "$OVERLAP"' EXIT

{
  printed_header=0
  while IFS= read -r spec; do
    # The rest of the line is already a valid ERE alternation: kw1|kw2|kw3.
    terrain=${spec%%|*}; pattern=${spec#*|}
    matches=$(grep -iE -- "$pattern" "$OUT" 2>/dev/null | grep '^- ' || true)
    [ -z "$matches" ] && continue
    count=$(printf '%s\n' "$matches" | wc -l | tr -d ' ')
    [ "$count" -lt 2 ] && continue

    # How many of them does the published (or local) arbitration actually name?
    arbitrated=0
    while IFS= read -r line; do
      # shellcheck disable=SC2016  # a sed script, not a shell expansion
      name=$(printf '%s' "$line" | sed -n 's/^- `\([^`]*\)`.*/\1/p')
      [ -z "$name" ] && continue
      if grep -qF -- "$name" "$ARB" 2>/dev/null || grep -qF -- "$name" "$LOCAL_ARB" 2>/dev/null; then
        arbitrated=$((arbitrated+1))
      fi
    done <<< "$matches"

    [ "$arbitrated" -ge 2 ] && continue   # already a real contest in the prose

    if [ "$printed_header" = 0 ]; then
      echo
      echo "## Possible unarbitrated overlap"
      echo
      echo "Detected by keyword on the descriptions above. A **signal, not a verdict** —"
      echo "these skills may overlap, and no published argument settles them."
      echo "Writing one is the most useful contribution this skill can receive."
      printed_header=1
    fi
    echo
    echo "### $terrain — $count installed, $arbitrated arbitrated"
    # shellcheck disable=SC2016  # a sed script, not a shell expansion
    printf '%s\n' "$matches" | sed -n 's/^- `\([^`]*\)`.*/- `\1`/p'
  done < <(terrains)
} > "$OVERLAP"

cat "$OVERLAP" >> "$OUT"

# Count only the catalogue proper. The overlap section repeats names already
# counted above, so counting the whole file inflates the total.
# `|| true` again: grep -c exits 1 on zero matches, and an empty machine is a
# legitimate result, not a failure. Assigning it to a variable propagates that
# status under `set -e`, where the old inline form inside echo hid it.
n=$(sed '/^## Possible unarbitrated overlap/,$d' "$OUT" | grep -c '^- ' || true)
echo "wrote $OUT ($n skills)"
# `|| true` is load-bearing under `set -e`: no overlap is the good case, and
# without it a clean run exits non-zero on its very last line.
if grep -q '^## Possible unarbitrated overlap' "$OUT"; then
  echo "  note: unarbitrated overlap detected — see the end of the file"
fi || true
