#!/usr/bin/env bash
# Regenerates references/catalogue.md from what is actually installed on disk.
# The router can only route over skills it knows exist, and skills come and go,
# so this is the one part of the skill that must never be hand-maintained.
#
# Run it after installing this skill, and again whenever you add or remove a
# pack. Shipping a catalogue from someone else's machine is the single way this
# skill produces confident, useless answers.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$HERE/references/catalogue.md"
SKILLS="${CLAUDE_SKILLS_DIR:-$HOME/.claude/skills}"
PLUGINS="${CLAUDE_PLUGINS_DIR:-$HOME/.claude/plugins/cache}"

# Pack attribution. gstack tags itself in its own description, so it is detected.
# The Matt Pocock engineering suite does not tag itself, so it is listed by name;
# that list is the one hand-maintained thing here, and it degrades gracefully —
# a skill missing from it simply lands under "Standalone".
MATT="ask-matt setup-matt-pocock-skills grilling grill-me grill-with-docs prototype
handoff to-spec to-tickets implement tdd code-review triage diagnosing-bugs wayfinder
improve-codebase-architecture codebase-design domain-modeling research to-questionnaire
wizard wait-what teach resolving-merge-conflicts writing-for-agents loop-me
migrate-to-shoehorn scaffold-exercises setup-pre-commit pick-ui-library"

desc() { awk '/^description:/{sub(/^description: **/,""); gsub(/^["'"'"']|["'"'"']$/,""); print; exit}' "$1"; }

emit() { # name, file
  local d; d=$(desc "$2")
  [ ${#d} -gt 240 ] && d="${d:0:237}..."
  printf -- '- `/%s` — %s\n' "$1" "$d"
}

{
  echo "# Installed skill catalogue"
  echo
  echo "Regenerated by \`scripts/build-catalogue.sh\`. Do not edit by hand."
  echo "Last generated: $(date +%Y-%m-%d)."
  echo
  echo "Never invoke a name that does not appear in this file."
  echo

  echo "## gstack"
  echo
  for f in "$SKILLS"/*/SKILL.md; do
    [ -e "$f" ] || continue
    n=$(basename "$(dirname "$f")"); case "$n" in _*) continue;; esac
    desc "$f" | grep -q '(gstack)' && emit "$n" "$f"
  done

  echo
  echo "## superpowers"
  echo
  for f in "$PLUGINS"/*/superpowers/*/skills/*/SKILL.md; do
    [ -e "$f" ] || continue
    emit "superpowers:$(basename "$(dirname "$f")")" "$f"
  done

  echo
  echo "## Matt Pocock engineering suite"
  echo
  for n in $MATT; do
    f="$SKILLS/$n/SKILL.md"; [ -e "$f" ] && emit "$n" "$f"
  done

  echo
  echo "## Standalone"
  echo
  for f in "$SKILLS"/*/SKILL.md; do
    [ -e "$f" ] || continue
    n=$(basename "$(dirname "$f")"); case "$n" in _*) continue;; esac
    desc "$f" | grep -q '(gstack)' && continue
    echo "$MATT" | tr ' \n' '\n\n' | grep -qx "$n" && continue
    emit "$n" "$f"
  done
  # Plugin skills are invoked as `plugin:skill`, so that is how they must be
  # named here. temp_git_* are half-finished marketplace clones, not installs.
  for f in "$PLUGINS"/*/*/*/skills/*/SKILL.md; do
    [ -e "$f" ] || continue
    case "$f" in */superpowers/*|*/temp_git_*) continue;; esac
    plug=$(basename "$(dirname "$(dirname "$(dirname "$(dirname "$f")")")")")
    emit "$plug:$(basename "$(dirname "$f")")" "$f"
  done
} | awk '!/^- /{print; next} {k=$2} !seen[k]++' > "$OUT"

echo "wrote $OUT ($(grep -c '^- ' "$OUT") skills)"
