#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

ORG_DEFAULT="whichskill"
REPO_DEFAULT="whichskill"

banner "whichskill — GitHub and Cloudflare Pages"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Claim the organisation"
say "This is the only step with a clock on it. github.com/whichskill was free"
say "when we checked; a free org costs nothing and cannot be reserved otherwise."
open_url "https://github.com/organizations/plan"
step "Pick the Free plan."
step "Organization account name: whichskill"
step "Contact email: yours. 'My personal account' for who it belongs to."
step "Skip the invite-members step."
note "If the name is already taken, pick another and use it everywhere below."
ask ORG "Organisation name you actually claimed [whichskill]:"
[[ -z "$ORG" ]] && ORG="$ORG_DEFAULT"
write_env GITHUB_ORG "$ORG"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the repository"
say "Empty — no README, no .gitignore, no licence. This repo already has all"
say "three, and letting GitHub add its own would make the first push conflict."
open_url "https://github.com/organizations/$ORG/repositories/new"
step "Repository name: whichskill"
step "Public."
step "Do NOT tick 'Add a README file'."
step "Add .gitignore: None. Choose a licence: None."
step "Create repository."
ask REPO "Repository name [whichskill]:"
[[ -z "$REPO" ]] && REPO="$REPO_DEFAULT"
write_env GITHUB_REPO "$ORG/$REPO"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Push what you already have"
say "Two commits are waiting locally: the empty initial commit and the v1."
if git remote get-url origin >/dev/null 2>&1; then
  note "A remote called 'origin' already exists: $(git remote get-url origin)"
  if confirm "Replace it with https://github.com/$ORG/$REPO.git ?"; then
    git remote set-url origin "https://github.com/$ORG/$REPO.git"
  fi
else
  git remote add origin "https://github.com/$ORG/$REPO.git"
  say "Added remote origin → https://github.com/$ORG/$REPO.git"
fi
if confirm "Push main now?"; then
  git push -u origin main && say "Pushed."
else
  SKIPPED+=("git push -u origin main")
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Description and topics"
say "Not decoration. Success criterion 3 is an external signal at J+60, and"
say "topics are how someone who has never heard of this finds it at all."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh repo edit "$ORG/$REPO" \
    --description "Ordered chains of agent skills, indexed by situation, with arbitration between near-duplicates." \
    --add-topic claude-code --add-topic agent-skills --add-topic ai-agents \
    --add-topic developer-tools --add-topic astro >/dev/null 2>&1 \
    && say "Description and topics set." \
    || SKIPPED+=("repo description and topics (gh repo edit failed)")
else
  SKIPPED+=("repo description and topics — gh not authenticated")
fi
note "Homepage stays empty until Cloudflare gives you a URL in the next stage."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Connect Cloudflare Pages"
say "Cloudflare runs 'npm run build' on every push. That command runs the corpus"
say "integrity check, so a chain pointing at a skill that does not exist fails"
say "the build and never deploys. That is the whole guarantee — no deploy token,"
say "no secret, nothing for you to wire up."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create/pages"
step "Connect to Git → GitHub → authorise Cloudflare."
step "Grant access to the $ORG organisation, repository $REPO."
step "Select the $REPO repository, then Begin setup."
step "Framework preset: Astro."
step "Build command: npm run build"
step "Build output directory: dist"
step "Save and Deploy, then wait for the first build to go green."
ask SITE_URL "Paste the .pages.dev URL Cloudflare gave you:"
write_env SITE_URL "$SITE_URL"
if [[ -n "$SITE_URL" ]] && command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh repo edit "$ORG/$REPO" --homepage "$SITE_URL" >/dev/null 2>&1 \
    && say "Set the repo homepage to $SITE_URL"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Prove the gate — the half that has never been tested"
say "The build test already proves the build fails on a dead reference. What it"
say "cannot prove from your laptop is the half that matters: that NOTHING gets"
say "published when it does. You are about to check that by hand, once."
say ""
step "The wizard will create a branch with a deliberately broken chain."
if confirm "Create the broken branch and push it?"; then
  git checkout -b gate-check >/dev/null 2>&1 || git checkout gate-check >/dev/null 2>&1
  cat > src/content/chains/__gate_check.md <<'BROKEN'
---
situation: Gate check
title: Gate check.
verdict: This chain must never reach the site.
steps:
  - ref: gstack/this-skill-does-not-exist
    why: A reference to a skill that is not in skills.json.
---

Delete this file once the check is done.
BROKEN
  git add src/content/chains/__gate_check.md
  git commit -q -m "test: deliberately broken reference, to prove the gate"
  git push -u origin gate-check
  say "Pushed the branch."
  open_url "https://github.com/$ORG/$REPO/branches"
  step "Open a pull request from gate-check into main."
  step "Watch the CI check: it must go RED."
  pause "Is the check red?"
  open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
  step "Open the $REPO project → Deployments."
  step "Confirm the preview deployment for gate-check FAILED."
  step "Confirm production is still on your last good commit, untouched."
  pause "Confirmed no deployment went out?"
  say ""
  step "Close the pull request without merging."
  if confirm "Delete the branch and the broken file now?"; then
    git checkout main >/dev/null 2>&1
    git branch -D gate-check >/dev/null 2>&1 || true
    git push origin --delete gate-check >/dev/null 2>&1 || true
    say "Cleaned up."
  else
    SKIPPED+=("delete the gate-check branch and __gate_check.md")
  fi
else
  SKIPPED+=("prove the deploy gate by hand — success criterion 2 stays half-verified")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Protect main"
say "Without this the gate only binds you. A contributor could merge a red PR,"
say "and the guarantee the whole project rests on would hold by politeness."
open_url "https://github.com/$ORG/$REPO/settings/rules/new?target=branch"
step "Ruleset name: main"
step "Enforcement status: Active."
step "Target branches: Include default branch."
step "Tick 'Require status checks to pass'."
step "Add checks → search 'verify' → select the CI job."
step "Tick 'Require a pull request before merging'."
step "Create."
note "As a solo maintainer you can still bypass it. The point is that a red"
note "check is visible and deliberate rather than silent."
pause "Done?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Turn on analytics"
say "Criterion 3 is an external signal at J+60. Without an instrument decided"
say "on day one, you will be guessing in two months."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Open the $REPO project → Metrics (or Analytics) → enable Web Analytics."
note "Cloudflare's version needs no client-side script, which keeps this a site"
note "with no JavaScript at all."
open_url "https://github.com/$ORG/$REPO/graphs/traffic"
step "Bookmark this page: it is the other half of the signal (views, clones)."
pause "Done?"

finish
